name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

  # schedule:
  #     - cron: "0 4 * * *"

permissions:
  contents: write

jobs:
  build-and-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Create production env
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: |
          echo "VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-https://dummy.supabase.co}" > .env.production
          echo "VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY:-dummy_key}" >> .env.production

      - name: Build
        run: npm run build

      - name: Log build success
        if: success()
        run: |
          mkdir -p assets/log
          echo "Build successful on $(date)" >> assets/log/ci.log

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages

      - name: Log deploy success
        if: success()
        run: |
          mkdir -p assets/log
          echo "Deploy successful on $(date)" >> assets/log/ci.log

      - name: Commit logs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/log/ci.log || true
          # If there are staged changes commit and push, otherwise no-op
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update CI log [skip ci]"
            git push
          fi
